#!/bin/bash


sudo make install -C /home/bec/temp/AtlantisTrunkPristine_New

if [ $? -eq 0 ] ; then

#gdb --args 
#valgrind --log-file=valgrind%p.log --track-origins=yes --leak-check=full --track-fds=yes --show-reachable=yes   

atlantisMerged -i INIT_VMPA_Jan2015.nc 0 -o outputSETAS.nc -r VMPA_setas_run_fishing_F_Trunk.prm -f VMPA_setas_force_fish_Trunk.prm -p VMPA_setas_physics.prm -b VMPA_setas_biol_fishing_Trunk.prm -h harvest_stripped.prm -s SETasGroupsDem.csv -q SETasFisheries.csv -d outputFolderPristine


else 
  echo 'Failed to compile trunk'  
fi




